# Generated by Django 3.1.2 on 2020-10-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('visibility', models.IntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_deg', models.IntegerField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
