# Generated by Django 3.1.2 on 2020-10-31 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_auto_20201030_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('PARKED', 'Parked'), ('TAKE_OFF', 'Take-off'), ('AIRBORNE', 'Airborne'), ('APPROACH', 'Approach'), ('LANDED', 'Landed')], max_length=50)),
                ('to_state', models.CharField(choices=[('PARKED', 'Parked'), ('TAKE_OFF', 'Take-off'), ('AIRBORNE', 'Airborne'), ('APPROACH', 'Approach'), ('LANDED', 'Landed')], max_length=50)),
                ('outcome', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.aircraft')),
            ],
        ),
    ]
